### ISSUE TITLE
cufft_float timer error

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft#6] opened 2016-06-16 19:11 UTC
Hi, I just built gearshifft with gcc 5.3.0 and cuda 7.5.18 and boost 1.59.0 and clfft 2.12.1. When I launch 

```
 ./gearshifft_cufft_float
```

I get:

```
$ ./gearshifft_cufft_float 
Running 16 test cases...
/home/steinbac/development/gearshifft/src/../inc/fixture_benchmark.hpp(72): error: in "CuFFT/TestCuFFT1024<N10gearshifft3FFTINS_16FFT_Inplace_RealENS_5CuFFT9CuFFTImplENS_5TimerINS_10TimerCUDA_EEEEE>": check deviation <= error_bound has failed [0.0049029093974303616 > 1.0000000000000001e-05]

*** 1 failure is detected in the test module "Fixtures"
```

where is this coming from?

**Comment by tdd11235813** [comment] 2016-06-17 20:39
not good. this is on the M2090, right? Looks like he fails on n=1024 for real + inplace FFT, weird.
Can you reproduce this error with the following line in [fixture_test_suite.hpp](https://github.com/mpicbg-scicomp/gearshifft/blob/master/inc/fixture_test_suite.hpp#L26)
#define EXTENTS ((1024))
?

**Comment by tdd11235813** [comment] 2016-08-03 15:52
If you have time, can you rerun with the current version of gearshifft on that M2090 to see if the bug persists?

```
./gearshifft_cufft_float -- -e 1024 -v
```

**Comment by tdd11235813** [comment] 2017-06-15 11:05
I am going to close this. Please reopen if issue occurs in the current version.

**Closed as completed by tdd11235813** 2017-06-15 11:05 UTC
